version: '3.8'

services:
  django:
    build: ./django_app
    container_name: django_app
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  fastapi:
    build: ./fastapi_app
    container_name: fastapi_app
    volumes:
      - ./fastapi_app:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: mis_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mis_db
      POSTGRES_USER: mis_user
      POSTGRES_PASSWORD: mis_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
