version: '3.8'
services:
  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
      - fastapi
      - frontend

  django:
    build: ./django_app
    container_name: django_app
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celeryworker:
    build: ./django_app
    container_name: celery_worker
    command: celery -A django_app worker -l info
    volumes:
      - ./django_app:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celerybeat:
    build: ./django_app
    container_name: celery_beat
    command: celery -A django_app beat -l info
    volumes:
      - ./django_app:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  fastapi:
    build: ./fastapi_app
    container_name: fastapi_app
    volumes:
      - ./fastapi_app:/app
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: mis_frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - django
      - fastapi

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mis_db
      POSTGRES_USER: mis_user
      POSTGRES_PASSWORD: mis_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
